### ISSUE TITLE
Zertifikate für Mock-Connector

### ISSUE THREAD

**Issue by christophgapp** [gematik/app-Authenticator#1]
Die für den Mockmodus notwendigen Test-Zertifikate sind unter gematikde.sharepoint.com, leider habe ich darauf jedoch keinen Zugriff.
Wäre es möglich, diese (oder andere) Zertifikate im GitHub-Projekt zur Verfügung zu stellen?
Danke!

**Comment by JuergenSchaefer** [comment]
Hallo,
der Pfad zu dem Sharepoint ist öffentlich zugänglich über: https://gematikde.sharepoint.com/:f:/s/EXTAuthenticator/Eufh1_mbmhhImVH1ZDhgKOwBZogXt6S9PxgT7WkAY20tkA?e=2MGuBC 
Versuchen Sie es einmal im Inkognitomodus, falls es nicht geht.
Alternativ über unser Fachportal unter Downloads: https://fachportal.gematik.de/hersteller-anbieter/komponenten-dienste/authenticator#c6683
