### ISSUE TITLE
TI 2.0: Betroffene Person - Hauptwohnung

### ISSUE THREAD

**Issue by it-mh** [gematik/app-Authenticator#37]
**Der** Hauptwohnung bezeichnet den Ort, an dem die betroffene Person gemeldet ist.
-- ersetzen durch -->
**Die** Hauptwohnung bezeichnet den Ort, an dem die betroffene Person gemeldet ist.

![issue](https://github.com/gematik/app-Authenticator/assets/108720612/20bc0fec-57fa-4315-895e-d7a00fb2a9ba)

**Comment by Uwinator** [comment]
Hallo it-mh,
der beschriebene Fehler hat nichts mit dem Authenticator zu tun, sondern scheint im DEMIS Meldeportal vorzuliegen.
Der Authenticator ist eine Authentisierungslösung gegenüber der Telematikinfrastruktur, die von Fachanwendungen wie DEMIS genutzt wird. 

Bitte den Fehler an den DEMIS-Support melden:
Email: [demis-support@rki.de](mailto:demis-support@rki.de)
Hotline: 0800 - 000 3041 (Mo.-Fr., 09-17 Uhr)

Beste Grüße
Uwe

**Comment by it-mh** [comment]
Vielen Dank für die Rückmeldung.
